name: DelayedTNT
version: 1.2.3
main: de.timecoding.delayedtnt.DelayedTNT
api-version: 1.13
description: "A plugin which is able to spawn delayed tnt"

commands:
  spawntnt:
    aliases:
      - tnt
    description: "A command which allows players to spawn a delayed tnt"
  tntrain:
    description: "A command which allows players to spawn a tntrain"
  #tntatcoords: COMING SOON
    #aliases:
      #- tntatcoordinates
    #description: "A command which allows players to spawn a delayed tnt at a specific location"
