name: DelayedTNT
version: 1.2.1
main: de.timecoding.delayedtnt.DelayedTNT
api-version: 1.13
description: "A plugin which is able to spawn delayed tnt"

commands:
  spawntnt:
    aliases:
      - tnt
    description: "A command which allows players to spawn a delayed tnt"
